CREATE TABLE GOAT.HERD
(
id INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
tag varchar(10) NOT NULL,
scrapie varchar(20),
name varchar(40),
nkr varchar(40),
akga varchar(40),
ikga varchar(40),
tattool varchar(4),
tattoor varchar(4),
microchip varchar(30),
color varchar(20),
gender varchar(6),
herdgroup varchar(40),
birthdate varchar(10),
notes varchar(200),
dam varchar(40),
firstlactation varchar(4),
buck varchar(40),
birthweight varchar(4),
birthrank varchar(40),
birthnotes varchar(200),
dambreed varchar(40),
sirebreed varchar(40),
percentage varchar(40),
purchasedate varchar(10),
price varchar(7),
seller varchar(40),
sellernotes varchar(200),
sold varchar(3),
amount varchar(8),
fees varchar(7),
solddate varchar(10),
soldnote varchar(200),
death varchar (3),
deathdate varchar(10),
dnotes varchar(200),
referenceonly varchar(3),
owned varchar(3),
PRIMARY KEY (id)
);